### ISSUE TITLE
Migrate to wrct883

### ISSUE THREAD

**Issue by widdowson** [wrct883/warmd#50]
Hey Marcus,

I'm glad to see that warmd has been breathed back to life :). Would you consider pulling it into the wrct883 project, and continuing development there, since the wrct883 project has fully unlimited repos, users, etc?

Thanks :)
-Andrew

**Comment by widdowson** [comment]
Tagging @malexandert in the comments since I understandably can't assign it to him :)

**Comment by malexandert** [comment]
Done!
